In [118]:
import pandas as pd

In [119]:
df = pd.read_csv("/content/Day10_Flight_Operations_Dataset.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

# 3. Display First Few Rows

In [120]:
df.head()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

# 4. Display Last Few Rows

In [121]:
df.tail()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

# 5. Check Dataset Shape

In [122]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 180
Number of Columns: 17

# 6. View Column Names

In [123]:
print(df.columns.tolist())

['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']

# 7. Check Data Types

In [124]:
df.dtypes

Flight_ID                  object
Flight_Date                object
Airline                    object
Origin                     object
Destination                object
Aircraft                   object
Travel_Class               object
Passengers                  int64
Seat_Capacity               int64
Average_Ticket_Price        int64
Delay_Minutes             float64
Flight_Status              object
Weather                    object
Booking_Channel            object
Avg_Baggage_Kg              int64
Meal_Preference            object
Passenger_Satisfaction      int64
dtype: object

# 8. Dataset Information

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB

# 9. Descriptive Statistics

In [126]:
df.describe()

,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Avg_Baggage_Kg,Passenger_Satisfaction
count,180.000000,180.000000,180.000000,173.000000,180.000000,180.000000
mean,122.772222,197.238889,6111.677778,19.335260,15.150000,3.494444
std,45.635651,15.408176,3615.220040,29.029712,5.705506,1.169908
min,45.000000,180.000000,1949.000000,0.000000,5.000000,2.000000
25%,78.750000,186.000000,3815.500000,0.000000,10.000000,2.000000
50%,125.000000,189.000000,5380.000000,5.000000,15.500000,3.000000
75%,162.250000,210.000000,6790.000000,20.000000,20.000000,5.000000
max,210.000000,220.000000,27832.000000,110.000000,25.000000,5.000000

# 10. Check Missing Values

In [127]:
df.isnull().sum()

Flight_ID                 0
Flight_Date               0
Airline                   0
Origin                    0
Destination               0
Aircraft                  0
Travel_Class              0
Passengers                0
Seat_Capacity             0
Average_Ticket_Price      0
Delay_Minutes             7
Flight_Status             0
Weather                   0
Booking_Channel           0
Avg_Baggage_Kg            0
Meal_Preference           0
Passenger_Satisfaction    0
dtype: int64

### Observation

The missing value check helps identify whether any columns contain incomplete information. This is important before performing further analysis.

# 11. Check Duplicate Records

In [128]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

# 12. Convert Flight Date

In [129]:
df["Flight_Date"] = pd.to_datetime(df["Flight_Date"])
print(df["Flight_Date"].dtype)

datetime64[ns]

# 13. Create New Date Columns

This demonstrates **data transformation using Pandas**.

In [130]:
df["Year"] = df["Flight_Date"].dt.year
df["Month"] = df["Flight_Date"].dt.month

In [131]:
df["Day"] = df["Flight_Date"].dt.day_name()
display(df[["Flight_Date", "Year", "Month", "Day"]].head())

  Flight_Date  Year  Month       Day
0  2026-03-23  2026      3    Monday
1  2026-06-07  2026      6    Sunday
2  2026-05-12  2026      5   Tuesday
3  2026-05-30  2026      5  Saturday
4  2026-02-27  2026      2    Friday

# 14. Selecting Specific Columns

In [132]:
display(df[["Flight_ID", "Airline", "Origin", "Destination", "Passengers", "Delay_Minutes"]].head(10))

,Flight_ID,Airline,Origin,Destination,Passengers,Delay_Minutes
0,FL0001,SpiceJet,Mumbai,Bengaluru,210,50.0
1,FL0002,Akasa Air,Delhi,Mumbai,70,0.0
2,FL0003,Air India,Kochi,Delhi,67,5.0
3,FL0004,Akasa Air,Srinagar,Delhi,153,35.0
4,FL0005,Air India,Pune,Delhi,178,20.0
5,FL0006,Akasa Air,Kochi,Delhi,123,35.0
6,FL0007,Air India Express,Delhi,Srinagar,178,0.0
7,FL0008,Air India,Delhi,Chennai,157,0.0
8,FL0009,Akasa Air,Delhi,Chennai,82,75.0
9,FL0010,Akasa Air,Ahmedabad,Bengaluru,125,12.0

# 15. Select Rows Using loc

In [133]:
display(df.loc[df["Origin"] == "Mumbai", ["Flight_ID", "Airline", "Destination", "Passengers"]].head(10))

   Flight_ID            Airline Destination  Passengers
0     FL0001           SpiceJet   Bengaluru         210
10    FL0011          Air India   Bengaluru         195
15    FL0016          Akasa Air   Bengaluru          69
19    FL0020           SpiceJet     Kolkata         125
28    FL0029  Air India Express   Bengaluru         185
45    FL0046          Air India     Kolkata         162
52    FL0053          Akasa Air   Bengaluru          72
53    FL0054           SpiceJet   Bengaluru          49
56    FL0057           SpiceJet     Kolkata          51
59    FL0060             IndiGo     Kolkata         116

# 16. Filter Flights with High Passengers

In [134]:
high_passenger_flights = df[df["Passengers"] > 150]
display(high_passenger_flights[["Flight_ID", "Airline", "Passengers", "Seat_Capacity"]].head(10))

   Flight_ID            Airline  Passengers  Seat_Capacity
0     FL0001           SpiceJet         210            180
3     FL0004          Akasa Air         153            220
4     FL0005          Air India         178            180
6     FL0007  Air India Express         178            210
7     FL0008          Air India         157            220
10    FL0011          Air India         195            189
12    FL0013           SpiceJet         162            220
20    FL0021            Vistara         173            189
26    FL0027           SpiceJet         169            180
28    FL0029  Air India Express         185            189

# 17. Filter Delayed Flights

In [135]:
delayed_flights = df[df["Flight_Status"] == "Delayed"]
display(delayed_flights[["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes"]].head(10))

   Flight_ID            Airline     Origin Destination  Delay_Minutes
0     FL0001           SpiceJet     Mumbai   Bengaluru           50.0
3     FL0004          Akasa Air   Srinagar       Delhi           35.0
4     FL0005          Air India       Pune       Delhi           20.0
5     FL0006          Akasa Air      Kochi       Delhi           35.0
8     FL0009          Akasa Air      Delhi     Chennai           75.0
16    FL0017           SpiceJet      Delhi     Chennai           20.0
17    FL0018  Air India Express     Jaipur      Mumbai           20.0
21    FL0022            Vistara      Kochi       Delhi           75.0
26    FL0027           SpiceJet  Bengaluru   Hyderabad          110.0
29    FL0030           SpiceJet      Delhi    Srinagar           75.0

# 18. Flights with Long Delays

In [136]:
long_delays = df[df["Delay_Minutes"] > 30]
print("Flights with delay above 30 minutes:", len(long_delays))

Flights with delay above 30 minutes: 40

# 19. Filter Flights by Airline

In [137]:
air_india = df[df["Airline"] == "Air India"]
display(air_india.head())

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction,Year,Month,Day
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2,2026,5,Tuesday
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5,2026,2,Friday
7,FL0008,2026-04-28,Air India,Delhi,Chennai,Airbus A319,Business,157,220,14173,0.0,On Time,Fog,Airline Website,25,Vegan,5,2026,4,Tuesday
10,FL0011,2026-04-17,Air India,Mumbai,Bengaluru,Airbus A321,Economy,195,189,3393,5.0,On Time,Clear,Airline Website,17,Vegetarian,2,2026,4,Friday
13,FL0014,2026-06-14,Air India,Lucknow,Delhi,Airbus A321,Economy,78,220,2744,0.0,On Time,Cloudy,Online Travel Portal,13,No Meal,5,2026,6,Sunday

# 20. Filter by Multiple Conditions

In [138]:
result = df[(df["Flight_Status"] == "Delayed") & (df["Passengers"] > 150)]
display(result[["Flight_ID", "Airline", "Passengers", "Delay_Minutes"]])

    Flight_ID            Airline  Passengers  Delay_Minutes
0      FL0001           SpiceJet         210           50.0
3      FL0004          Akasa Air         153           35.0
4      FL0005          Air India         178           20.0
26     FL0027           SpiceJet         169          110.0
29     FL0030           SpiceJet         200           75.0
30     FL0031            Vistara         209           50.0
43     FL0044  Air India Express         176           35.0
57     FL0058             IndiGo         151          110.0
58     FL0059  Air India Express         159           20.0
69     FL0070           SpiceJet         201           20.0
80     FL0081           SpiceJet         199           50.0
102    FL0103             IndiGo         167           20.0
104    FL0105            Vistara         158           50.0
107    FL0108             IndiGo         198           75.0
119    FL0120          Air India         175           20.0
138    FL0139  Air India Express         169           20.0
153    FL0154          Air India         201           20.0
157    FL0158            Vistara         176           75.0
168    FL0169             IndiGo         152           35.0

# 21. Sorting by Passengers

In [139]:
display(df.sort_values("Passengers", ascending=False).head(10))

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction,Year,Month,Day
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3,2026,3,Monday
30,FL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4,2026,1,Thursday
92,FL0093,2026-04-30,Air India Express,Srinagar,Delhi,Airbus A319,Business,209,220,12970,0.0,On Time,Clear,Travel Agency,8,Vegan,2,2026,4,Thursday
148,FL0149,2026-02-10,Akasa Air,Jaipur,Mumbai,Airbus A319,Economy,202,210,6239,5.0,On Time,Rain,Online Travel Portal,8,No Meal,5,2026,2,Tuesday
69,FL0070,2026-06-12,SpiceJet,Srinagar,Delhi,Boeing 737,Economy,201,189,2959,20.0,Delayed,Rain,Online Travel Portal,12,Vegan,4,2026,6,Friday
153,FL0154,2026-04-09,Air India,Mumbai,Bengaluru,Airbus A321,Economy,201,186,3823,20.0,Delayed,Clear,Online Travel Portal,13,Vegan,2,2026,4,Thursday
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3,2026,4,Friday
94,FL0095,2026-06-14,Vistara,Bengaluru,Kochi,Airbus A319,Economy,199,189,4369,0.0,On Time,Fog,Online Travel Portal,11,Vegetarian,5,2026,6,Sunday
80,FL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4,2026,4,Friday
107,FL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2,2026,5,Saturday

### Observation

Sorting the dataset helps identify flights with the highest passenger volumes.

# 22. Sorting by Ticket Price

In [140]:
display(df.sort_values("Average_Ticket_Price", ascending=False)[["Flight_ID", "Airline", "Travel_Class", "Average_Ticket_Price"]].head(10))

    Flight_ID            Airline Travel_Class  Average_Ticket_Price
138    FL0139  Air India Express     Business                 27832
52     FL0053          Akasa Air     Business                 21499
32     FL0033          Akasa Air     Business                 17625
176    FL0177            Vistara     Business                 17306
108    FL0109           SpiceJet     Business                 16390
132    FL0133             IndiGo     Business                 15324
155    FL0156            Vistara     Business                 15040
7      FL0008          Air India     Business                 14173
51     FL0052           SpiceJet     Business                 13824
92     FL0093  Air India Express     Business                 12970

# 23. Sorting by Delay

In [141]:
display(df.sort_values("Delay_Minutes", ascending=False)[["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes"]].head(10))

    Flight_ID            Airline     Origin Destination  Delay_Minutes
26     FL0027           SpiceJet  Bengaluru   Hyderabad          110.0
177    FL0178             IndiGo      Delhi      Mumbai          110.0
82     FL0083  Air India Express    Lucknow       Delhi          110.0
57     FL0058             IndiGo  Hyderabad     Kolkata          110.0
50     FL0051          Air India      Delhi      Mumbai          110.0
128    FL0129           SpiceJet    Lucknow       Delhi          110.0
146    FL0147             IndiGo     Mumbai     Kolkata          110.0
169    FL0170             IndiGo     Mumbai     Kolkata          110.0
161    FL0162          Air India  Hyderabad     Kolkata          110.0
21     FL0022            Vistara      Kochi       Delhi           75.0

# 24. Airline-wise Flight Count

In [142]:
airline_flights = df["Airline"].value_counts()
display(airline_flights)

Airline
Vistara              37
SpiceJet             32
IndiGo               32
Akasa Air            31
Air India Express    24
Air India            24
Name: count, dtype: int64

# 25. Airline-wise Passenger Count

In [143]:
album_passengers = df.groupby("Airline")["Passengers"].sum()
display(album_passengers.sort_values(ascending=False))

Airline
Vistara              4484
IndiGo               4158
SpiceJet             3929
Akasa Air            3427
Air India            3074
Air India Express    3027
Name: Passengers, dtype: int64

# 26. Airline-wise Average Ticket Price

In [144]:
album_price = df.groupby("Airline")["Average_Ticket_Price"].mean()
display(album_price.sort_values(ascending=False).round(2))

Airline
Air India Express    7388.46
Vistara              6265.65
SpiceJet             6189.75
IndiGo               5931.66
Akasa Air            5841.00
Air India            5083.08
Name: Average_Ticket_Price, dtype: float64

# 27. Airline-wise Average Delay

In [145]:
album_delay = df.groupby("Airline")["Delay_Minutes"].mean()
display(album_delay.sort_values(ascending=False).round(2))

Airline
IndiGo               25.03
SpiceJet             24.14
Air India            21.26
Vistara              18.63
Akasa Air            14.40
Air India Express    11.29
Name: Delay_Minutes, dtype: float64

# 28. Airline Performance Summary

This is one of the most useful groupby operations in the notebook.

In [146]:
album_summary = df.groupby("Airline").agg({"Flight_ID": "count", "Passengers": "sum", "Average_Ticket_Price": "mean", "Delay_Minutes": "mean", "Passenger_Satisfaction": "mean"})
display(album_summary)

,Flight_ID,Passengers,Average_Ticket_Price,Delay_Minutes,Passenger_Satisfaction
Airline,,,,,
Air India,24,3074,5083.083333,21.260870,3.750000
Air India Express,24,3027,7388.458333,11.291667,3.666667
Akasa Air,31,3427,5841.000000,14.400000,3.419355
IndiGo,32,4158,5931.656250,25.031250,3.343750
SpiceJet,32,3929,6189.750000,24.137931,3.531250
Vistara,37,4484,6265.648649,18.628571,3.378378

In [147]:
album_summary.columns = ["Total_Flights", "Total_Passengers", "Average_Ticket_Price", "Average_Delay", "Average_Satisfaction"]
display(album_summary.round(2))

,Total_Flights,Total_Passengers,Average_Ticket_Price,Average_Delay,Average_Satisfaction
Airline,,,,,
Air India,24,3074,5083.08,21.26,3.75
Air India Express,24,3027,7388.46,11.29,3.67
Akasa Air,31,3427,5841.00,14.40,3.42
IndiGo,32,4158,5931.66,25.03,3.34
SpiceJet,32,3929,6189.75,24.14,3.53
Vistara,37,4484,6265.65,18.63,3.38

# 29. Flight Status Analysis

In [148]:
display(df["Flight_Status"].value_counts())

Flight_Status
On Time      114
Delayed       59
Cancelled      7
Name: count, dtype: int64

In [149]:
status_percentage = (df["Flight_Status"].value_counts(normalize=True) * 100)
display(status_percentage.round(2))

Flight_Status
On Time      63.33
Delayed      32.78
Cancelled     3.89
Name: proportion, dtype: float64

# 30. Weather-wise Flight Analysis

In [150]:
display(df["Weather"].value_counts())

Weather
Rain      43
Cloudy    38
Fog       35
Clear     34
Storm     30
Name: count, dtype: int64

In [151]:
weather_delay = df.groupby("Weather")["Delay_Minutes"].mean()
display(weather_delay.sort_values(ascending=False).round(2))

Weather
Rain      22.22
Storm     20.10
Cloudy    20.03
Clear     18.03
Fog       15.79
Name: Delay_Minutes, dtype: float64

### Interpretation

Grouping flights by weather condition helps determine whether weather conditions are associated with higher average delays.

# 31. Booking Channel Analysis

In [152]:
display(df["Booking_Channel"].value_counts())

Booking_Channel
Online Travel Portal    50
Mobile App              45
Travel Agency           44
Airline Website         41
Name: count, dtype: int64

In [153]:
booking_price = df.groupby("Booking_Channel")["Average_Ticket_Price"].mean()
display(booking_price.sort_values(ascending=False).round(2))

Booking_Channel
Mobile App              6637.24
Travel Agency           6223.89
Airline Website         5994.17
Online Travel Portal    5636.28
Name: Average_Ticket_Price, dtype: float64

# 32. Origin-wise Flight Analysis

In [154]:
origin_count = df["Origin"].value_counts()
display(origin_count)

Origin
Delhi        43
Mumbai       29
Bengaluru    21
Srinagar     15
Kochi        14
Ahmedabad    12
Pune         11
Lucknow      11
Chennai       9
Jaipur        8
Hyderabad     7
Name: count, dtype: int64

# 33. Destination-wise Flight Analysis

In [155]:
destination_count = df["Destination"].value_counts()
display(destination_count)

Destination
Delhi        51
Mumbai       30
Bengaluru    28
Kolkata      20
Chennai      17
Srinagar     13
Hyderabad    13
Kochi         8
Name: count, dtype: int64

# 34. Route Analysis

In [156]:
route_count = df.groupby(["Origin", "Destination"]).size()
display(route_count.sort_values(ascending=False).head(10))

Origin     Destination
Delhi      Chennai        17
Mumbai     Bengaluru      16
Srinagar   Delhi          15
Kochi      Delhi          14
Delhi      Srinagar       13
           Mumbai         13
Bengaluru  Hyderabad      13
Mumbai     Kolkata        13
Ahmedabad  Bengaluru      12
Lucknow    Delhi          11
dtype: int64

# 35. Route-wise Passenger Analysis

In [157]:
route_passengers = df.groupby(["Origin", "Destination"])["Passengers"].sum()
display(route_passengers.sort_values(ascending=False).head(10))

Origin     Destination
Delhi      Chennai        2011
Srinagar   Delhi          1957
Mumbai     Bengaluru      1933
Delhi      Srinagar       1828
Bengaluru  Hyderabad      1795
Mumbai     Kolkata        1683
Kochi      Delhi          1657
Delhi      Mumbai         1609
Pune       Delhi          1564
Ahmedabad  Bengaluru      1411
Name: Passengers, dtype: int64

# 36. Aircraft Analysis

In [158]:
display(df["Aircraft"].value_counts())

Aircraft
Airbus A319    60
Boeing 737     44
Airbus A320    40
Airbus A321    36
Name: count, dtype: int64

In [159]:
aircraft_delay = df.groupby("Aircraft")["Delay_Minutes"].mean()
display(aircraft_delay.sort_values(ascending=False).round(2))

Aircraft
Airbus A319    23.56
Airbus A321    23.24
Boeing 737     17.66
Airbus A320    11.11
Name: Delay_Minutes, dtype: float64

# 37. Travel Class Analysis

In [160]:
class_passengers = df.groupby("Travel_Class")["Passengers"].sum()
display(class_passengers.sort_values(ascending=False))

Travel_Class
Economy            16054
Premium Economy     4574
Business            1471
Name: Passengers, dtype: int64

In [161]:
class_price = df.groupby("Travel_Class")["Average_Ticket_Price"].mean()
display(class_price.sort_values(ascending=False).round(2))

Travel_Class
Business           16780.00
Premium Economy     8736.74
Economy             4550.27
Name: Average_Ticket_Price, dtype: float64

# 38. Passenger Satisfaction Analysis

In [162]:
satisfaction_airline = df.groupby("Airline")["Passenger_Satisfaction"].mean()
display(satisfaction_airline.sort_values(ascending=False).round(2))

Airline
Air India            3.75
Air India Express    3.67
SpiceJet             3.53
Akasa Air            3.42
Vistara              3.38
IndiGo               3.34
Name: Passenger_Satisfaction, dtype: float64

# 39. Delay and Satisfaction

In [163]:
delay_satisfaction = df.groupby("Flight_Status")["Passenger_Satisfaction"].mean()
display(delay_satisfaction.round(2))

Flight_Status
Cancelled    3.86
Delayed      3.27
On Time      3.59
Name: Passenger_Satisfaction, dtype: float64

### Interpretation

Comparing passenger satisfaction between flight statuses helps understand whether delayed flights are associated with lower passenger satisfaction.

# 40. Passenger Load Factor

This is a useful **data transformation** and makes your analysis more meaningful.

### Formula

```text
Passenger Load Factor =
Passengers / Seat Capacity × 100
```

In [164]:
df["Load_Factor"] = (df["Passengers"] / df["Seat_Capacity"]) * 100
display(df[["Flight_ID", "Passengers", "Seat_Capacity", "Load_Factor"]].head())

  Flight_ID  Passengers  Seat_Capacity  Load_Factor
0    FL0001         210            180   116.666667
1    FL0002          70            210    33.333333
2    FL0003          67            220    30.454545
3    FL0004         153            220    69.545455
4    FL0005         178            180    98.888889

# 41. Average Load Factor

In [165]:
print("Average Load Factor:", round(df["Load_Factor"].mean(), 2), "%")

Average Load Factor: 62.66 %

# 42. Find Highly Utilized Flights

In [166]:
high_load = df[df["Load_Factor"] > 90]
display(high_load[["Flight_ID", "Airline", "Passengers", "Seat_Capacity", "Load_Factor"]].head(10))

   Flight_ID            Airline  Passengers  Seat_Capacity  Load_Factor
0     FL0001           SpiceJet         210            180   116.666667
4     FL0005          Air India         178            180    98.888889
10    FL0011          Air India         195            189   103.174603
20    FL0021            Vistara         173            189    91.534392
26    FL0027           SpiceJet         169            180    93.888889
28    FL0029  Air India Express         185            189    97.883598
29    FL0030           SpiceJet         200            210    95.238095
30    FL0031            Vistara         209            180   116.111111
43    FL0044  Air India Express         176            186    94.623656
55    FL0056  Air India Express         180            180   100.000000

# 43. Revenue Estimate

We can create another useful transformed column.

### Formula

```text
Estimated Revenue =
Passengers × Average Ticket Price
```

In [167]:
df["Estimated_Revenue"] = (df["Passengers"] * df["Average_Ticket_Price"])
display(df[["Flight_ID", "Passengers", "Average_Ticket_Price", "Estimated_Revenue"]].head())

  Flight_ID  Passengers  Average_Ticket_Price  Estimated_Revenue
0    FL0001         210                  6894            1447740
1    FL0002          70                  4468             312760
2    FL0003          67                  4713             315771
3    FL0004         153                  3791             580023
4    FL0005         178                  6505            1157890

# 44. Highest Revenue Flights

In [168]:
display(df.sort_values("Estimated_Revenue", ascending=False)[["Flight_ID", "Airline", "Origin", "Destination", "Passengers", "Estimated_Revenue"]].head(10))

,Flight_ID,Airline,Origin,Destination,Passengers,Estimated_Revenue
138,FL0139,Air India Express,Delhi,Chennai,169,4703608
92,FL0093,Air India Express,Srinagar,Delhi,209,2710730
132,FL0133,IndiGo,Pune,Delhi,164,2513136
51,FL0052,SpiceJet,Jaipur,Mumbai,163,2253312
7,FL0008,Air India,Delhi,Chennai,157,2225161
176,FL0177,Vistara,Chennai,Mumbai,124,2145944
36,FL0037,Vistara,Bengaluru,Kochi,184,2136976
108,FL0109,SpiceJet,Srinagar,Delhi,129,2114310
107,FL0108,IndiGo,Lucknow,Delhi,198,2089098
30,FL0031,Vistara,Delhi,Srinagar,209,2082058

# 45. Airline Revenue

In [169]:
album_revenue = df.groupby("Airline")["Estimated_Revenue"].sum()
display(album_revenue.sort_values(ascending=False).round(2))

Airline
Vistara              28689467
IndiGo               25709131
SpiceJet             24195935
Air India Express    23944164
Akasa Air            18872059
Air India            16232418
Name: Estimated_Revenue, dtype: int64

# 46. Monthly Flight Analysis

In [170]:
monthly_flights = df.groupby("Month").size()
display(monthly_flights)

Month
1    29
2    28
3    33
4    35
5    30
6    25
dtype: int64

In [171]:
monthly_passengers = df.groupby("Month")["Passengers"].sum()
display(monthly_passengers)

Month
1    3656
2    3502
3    3839
4    4354
5    3504
6    3244
Name: Passengers, dtype: int64

# 47. Monthly Revenue

In [172]:
monthly_revenue = df.groupby("Month")["Estimated_Revenue"].sum()
display(monthly_revenue.sort_index())

Month
1    23954177
2    23235729
3    21953715
4    27097851
5    20609473
6    20792229
Name: Estimated_Revenue, dtype: int64

# 48. Meal Preference Analysis

In [173]:
display(df["Meal_Preference"].value_counts())

Meal_Preference
Vegetarian        52
Non-Vegetarian    45
Vegan             43
No Meal           40
Name: count, dtype: int64

# 49. Baggage Analysis

In [174]:
print("Average Baggage:", round(df["Avg_Baggage_Kg"].mean(), 2), "Kg")

Average Baggage: 15.15 Kg

In [175]:
baggage_class = df.groupby("Travel_Class")["Avg_Baggage_Kg"].mean()
display(baggage_class.round(2))

Travel_Class
Business           14.45
Economy            14.89
Premium Economy    16.37
Name: Avg_Baggage_Kg, dtype: float64

# 50. Overall Flight Summary

In [176]:
print("========== FLIGHT OPERATIONS SUMMARY ==========")
print("Total Flights:", len(df))
print("Total Passengers:", df["Passengers"].sum())
print("Average Passengers per Flight:", round(df["Passengers"].mean(), 2))
print("Average Ticket Price: ₹", round(df["Average_Ticket_Price"].mean(), 2))
print("Average Delay:", round(df["Delay_Minutes"].mean(), 2), "minutes")
print("Average Passenger Satisfaction:", round(df["Passenger_Satisfaction"].mean(), 2))
print("Average Load Factor:", round(df["Load_Factor"].mean(), 2), "%")

========== FLIGHT OPERATIONS SUMMARY ==========
Total Flights: 180
Total Passengers: 22099
Average Passengers per Flight: 122.77
Average Ticket Price: ₹ 6111.68
Average Delay: 19.34 minutes
Average Passenger Satisfaction: 3.49
Average Load Factor: 62.66 %

# 51. Top Airline by Passengers

In [177]:
top_airline = album_passengers.idxmax()
print("Top Airline by Passengers:", top_airline)
print("Total Passengers:", album_passengers.max())

Top Airline by Passengers: Vistara
Total Passengers: 4484

# 52. Airline with Highest Average Delay

In [178]:
worst_delay_airline = album_delay.idxmax()
print("Highest Average Delay Airline:", worst_delay_airline)
print("Average Delay:", round(album_delay.max(), 2), "minutes")

Highest Average Delay Airline: IndiGo
Average Delay: 25.03 minutes

# 53. Most Used Route

In [179]:
top_route = route_count.idxmax()
print("Most Used Route:", top_route[0], "to", top_route[1])
print("Number of Flights:", route_count.max())

Most Used Route: Delhi to Chennai
Number of Flights: 17

# 54. Highest Revenue Airline

In [180]:
top_revenue_airline = album_revenue.idxmax()
print("Highest Revenue Airline:", top_revenue_airline)
print("Estimated Revenue: ₹", round(album_revenue.max(), 2))

Highest Revenue Airline: Vistara
Estimated Revenue: ₹ 28689467