# Processed E-commerce Dataset

In this notebook, I will process three e-commerce datasets: Orders, Customers, and Products.

I will use Pandas to load, merge, combine, transform, and export the data into one clean dataset.

In [1]:
import pandas as pd

# Load Orders Dataset

### Load Datasets

In [2]:
orders = pd.read_csv('Day9_Orders.csv')
print('Orders dataset loaded successfully!')

Orders dataset loaded successfully!

# Load Customers Dataset

In [3]:
customers = pd.read_csv('Day9_Customers.csv')
print('Customers dataset loaded successfully!')

Customers dataset loaded successfully!

# Load Products Dataset

In [4]:
products = pd.read_csv('Day9_Products.csv')
print('Products dataset loaded successfully!')

Products dataset loaded successfully!

# Explore Datasets

### Explore Datasets

In [5]:
display(orders.head())
display(customers.head())
display(products.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [6]:
print('Orders:', orders.shape)
print('Customers:', customers.shape)
print('Products:', products.shape)

Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

# Using `merge()`

### Merge Datasets

In [7]:
orders_customers = pd.merge(orders, customers, on='Customer_ID', how='left')
display(orders_customers.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [8]:
processed_data = pd.merge(orders_customers, products, on='Product_ID', how='left')
display(processed_data.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

# Using `concat()`

### Demonstrate Concatenation

In [9]:
orders_part1 = orders.iloc[:60]
orders_part2 = orders.iloc[60:]
combined_orders = pd.concat([orders_part1, orders_part2], ignore_index=True)
print('Original Orders:', len(orders))
print('After concat:', len(combined_orders))

Original Orders: 120
After concat: 120

# DateTime Operations

### DateTime Transformations

In [10]:
processed_data['Order_Date'] = pd.to_datetime(processed_data['Order_Date'])
processed_data['Order_Year'] = processed_data['Order_Date'].dt.year
processed_data['Order_Month'] = processed_data['Order_Date'].dt.month
processed_data['Order_Day'] = processed_data['Order_Date'].dt.day
processed_data['Day_of_Week'] = processed_data['Order_Date'].dt.day_name()
display(processed_data[['Order_Date', 'Order_Year', 'Order_Month', 'Day_of_Week']].head())

  Order_Date  Order_Year  Order_Month Day_of_Week
0 2026-02-19        2026            2    Thursday
1 2026-01-25        2026            1      Sunday
2 2026-02-26        2026            2    Thursday
3 2026-03-04        2026            3   Wednesday
4 2026-03-29        2026            3      Sunday

# Using `apply()`

### Calculate Sales and Categories

In [11]:
processed_data['Total_Sales'] = processed_data.apply(lambda row: row['Quantity'] * row['Unit_Price'], axis=1)
processed_data['Order_Size'] = processed_data['Total_Sales'].apply(lambda x: 'High' if x >= 5000 else 'Normal')
display(processed_data[['Product_Name', 'Quantity', 'Unit_Price', 'Total_Sales', 'Order_Size']].head())

              Product_Name  Quantity  Unit_Price  Total_Sales Order_Size
0              Cricket Bat         2        2499         4998     Normal
1           Wireless Mouse         2         899         1798     Normal
2              Smart Watch         1        3299         3299     Normal
3  Machine Learning Basics         3         999         2997     Normal
4             Coffee Maker         5        3499        17495       High

# Create a Clean Dataset

### Final Dataset Selection

In [12]:
cols = ['Order_ID', 'Order_Date', 'Order_Year', 'Order_Month', 'Order_Day', 'Day_of_Week', 'Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_ID', 'Product_Name', 'Category', 'Brand', 'Quantity', 'Unit_Price', 'Total_Sales', 'Payment_Method', 'Order_Status', 'Order_Size']
final_data = processed_data[cols]
display(final_data.head())

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,Region,...,Product_ID,Product_Name,Category,Brand,Quantity,Unit_Price,Total_Sales,Payment_Method,Order_Status,Order_Size
0,O0001,2026-02-19,2026,2,19,Thursday,C027,Harsh Vardhan,Noida,North,...,P019,Cricket Bat,Sports,BatPro,2,2499,4998,Credit Card,Delivered,Normal
1,O0002,2026-01-25,2026,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,...,P003,Wireless Mouse,Electronics,TechGear,2,899,1798,Debit Card,Delivered,Normal
2,O0003,2026-02-26,2026,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,...,P004,Smart Watch,Electronics,FitTech,1,3299,3299,Cash on Delivery,Delivered,Normal
3,O0004,2026-03-04,2026,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,...,P015,Machine Learning Basics,Books,AIPress,3,999,2997,Net Banking,Delivered,Normal
4,O0005,2026-03-29,2026,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,5,3499,17495,Credit Card,Delivered,High

### Basic Analysis and Export

In [13]:
print('Total Sales:', final_data['Total_Sales'].sum())
display(final_data.groupby('Category')['Total_Sales'].sum())

Total Sales: 741507

Category
Books              35004
Clothing          168033
Electronics       177821
Home & Kitchen    243913
Sports            116736
Name: Total_Sales, dtype: int64

# Export the Processed Dataset

In [14]:
final_data.to_csv('Day9_Processed_Ecommerce_Dataset.csv', index=False)
print('Processed dataset exported successfully!')

Processed dataset exported successfully!

# Simple Analysis of Processed Data

### Check for Missing Values

In [15]:
final_data.isnull().sum()

Order_ID           0
Order_Date         0
Order_Year         0
Order_Month        0
Order_Day          0
Day_of_Week        0
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
Product_ID         0
Product_Name       0
Category           0
Brand              0
Quantity           0
Unit_Price         0
Total_Sales        0
Payment_Method     0
Order_Status       0
Order_Size         0
dtype: int64

### Display Final Processed Dataset

In [16]:
final_data

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,Region,...,Product_ID,Product_Name,Category,Brand,Quantity,Unit_Price,Total_Sales,Payment_Method,Order_Status,Order_Size
0,O0001,2026-02-19,2026,2,19,Thursday,C027,Harsh Vardhan,Noida,North,...,P019,Cricket Bat,Sports,BatPro,2,2499,4998,Credit Card,Delivered,Normal
1,O0002,2026-01-25,2026,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,...,P003,Wireless Mouse,Electronics,TechGear,2,899,1798,Debit Card,Delivered,Normal
2,O0003,2026-02-26,2026,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,...,P004,Smart Watch,Electronics,FitTech,1,3299,3299,Cash on Delivery,Delivered,Normal
3,O0004,2026-03-04,2026,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,...,P015,Machine Learning Basics,Books,AIPress,3,999,2997,Net Banking,Delivered,Normal
4,O0005,2026-03-29,2026,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,5,3499,17495,Credit Card,Delivered,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,2026,2,19,Thursday,C025,Reyansh Jain,Kolkata,East,...,P010,Electric Kettle,Home & Kitchen,KitchenPro,1,1499,1499,Net Banking,Delivered,Normal
116,O0117,2026-02-21,2026,2,21,Saturday,C019,Yusuf Dar,Srinagar,North,...,P015,Machine Learning Basics,Books,AIPress,3,999,2997,Cash on Delivery,Shipped,Normal
117,O0118,2026-03-09,2026,3,9,Monday,C025,Reyansh Jain,Kolkata,East,...,P016,Atomic Habits,Books,MindReads,4,599,2396,Credit Card,Delivered,Normal
118,O0119,2026-02-03,2026,2,3,Tuesday,C015,Karan Joshi,Chandigarh,North,...,P019,Cricket Bat,Sports,BatPro,2,2499,4998,Debit Card,Delivered,Normal
119,O0120,2026-01-21,2026,1,21,Wednesday,C013,Rahul Das,Kolkata,East,...,P020,Dumbbell Set,Sports,StrongFit,1,1999,1999,Cash on Delivery,Cancelled,Normal

### Verify Exported File

In [17]:
check_data = pd.read_csv('Day9_Processed_Ecommerce_Dataset.csv')
display(check_data.head())

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,Region,...,Product_ID,Product_Name,Category,Brand,Quantity,Unit_Price,Total_Sales,Payment_Method,Order_Status,Order_Size
0,O0001,2026-02-19,2026,2,19,Thursday,C027,Harsh Vardhan,Noida,North,...,P019,Cricket Bat,Sports,BatPro,2,2499,4998,Credit Card,Delivered,Normal
1,O0002,2026-01-25,2026,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,...,P003,Wireless Mouse,Electronics,TechGear,2,899,1798,Debit Card,Delivered,Normal
2,O0003,2026-02-26,2026,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,...,P004,Smart Watch,Electronics,FitTech,1,3299,3299,Cash on Delivery,Delivered,Normal
3,O0004,2026-03-04,2026,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,...,P015,Machine Learning Basics,Books,AIPress,3,999,2997,Net Banking,Delivered,Normal
4,O0005,2026-03-29,2026,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,5,3499,17495,Credit Card,Delivered,High