In [19]:
import pandas as pd
import numpy as np
import os

# Check if file exists, else create sample data for demonstration
file_path = "/mnt/data/Day11_Messy_Company_Employee_Dataset.csv"
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
else:
    print(f"Warning: {file_path} not found. Using sample data.")
    data = {
        "Employee_ID": [101, 102, 101, 103],
        "Department": ["ENGINEERING", "engineering", "Engineering", "Sales"],
        "Gender": ["Male", "MALE", "Male", "Female"],
        "Age": [30, np.nan, 30, 25]
    }
    df = pd.DataFrame(data)

df.head()

Warning: /mnt/data/Day11_Messy_Company_Employee_Dataset.csv not found. Using sample data.

   Employee_ID   Department  Gender   Age
0          101  ENGINEERING    Male  30.0
1          102  engineering    MALE   NaN
2          101  Engineering    Male  30.0
3          103        Sales  Female  25.0

In [20]:
df.shape
df.columns

Index(['Employee_ID', 'Department', 'Gender', 'Age'], dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  4 non-null      int64
 1   Department   4 non-null      object
 2   Gender       4 non-null      object
 3   Age          3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [22]:
df.describe()

       Employee_ID        Age
count     4.000000   3.000000
mean    101.750000  28.333333
std       0.957427   2.886751
min     101.000000  25.000000
25%     101.000000  27.500000
50%     101.500000  30.000000
75%     102.250000  30.000000
max     103.000000  30.000000

In [23]:
df.isnull().sum()

Employee_ID    0
Department     0
Gender         0
Age            1
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df["Department"].value_counts(dropna=False)
df["Gender"].value_counts(dropna=False)

Gender
Male      2
MALE      1
Female    1
Name: count, dtype: int64

# Load Data

In [27]:
for col in ["City", "Work_Mode", "Job_Title", "Joining_Date"]:
    if col in df.columns:
        if col == "Joining_Date":
            print(f"\n--- {col} Analysis ---")
            print(df[col].head())
            print(df[col].dtype)
        else:
            print(f"\n--- {col} Value Counts ---")
            print(df[col].value_counts(dropna=False))
    else:
        print(f"Column '{col}' not found in current DataFrame.")

print("\n--- Missing Values Summary ---")
print(df.isnull().sum().sort_values(ascending=False))

Column 'City' not found in current DataFrame.
Column 'Work_Mode' not found in current DataFrame.
Column 'Job_Title' not found in current DataFrame.
Column 'Joining_Date' not found in current DataFrame.

--- Missing Values Summary ---
Age            1
Employee_ID    0
Department     0
Gender         0
dtype: int64

# Fill Nulls

In [28]:
cols_to_fill_mode = ["Department", "Gender", "City", "Work_Mode"]
cols_to_fill_median = ["Age", "Annual_Salary", "Experience_Years", "Performance_Score"]
for col in cols_to_fill_mode:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mode()[0])
for col in cols_to_fill_median:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())
display(df.isnull().sum())

Employee_ID    0
Department     0
Gender         0
Age            0
dtype: int64

# Fix Text

In [29]:
cols_to_fix = ["Department", "Gender", "City", "Work_Mode"]
for col in cols_to_fix:
    if col in df.columns:
        df[col] = df[col].str.strip().str.title()
        print(f"\n{col} Value Counts:")
        print(df[col].value_counts())

Department Value Counts:
Department
Engineering    3
Sales          1
Name: count, dtype: int64

Gender Value Counts:
Gender
Male      3
Female    1
Name: count, dtype: int64

# Set Types

In [30]:
if "Joining_Date" in df.columns:
    df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], errors="coerce")
for col in ["Age", "Annual_Salary", "Experience_Years", "Performance_Score"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
display(df.dtypes)
display(df.isnull().sum())

Employee_ID      int64
Department      object
Gender          object
Age            float64
dtype: object

Employee_ID    0
Department     0
Gender         0
Age            0
dtype: int64

# Clean Row

In [34]:
df = df.drop_duplicates().copy()
for col in ["Employee_Name", "Job_Title"]:
    if col in df.columns:
        df.loc[:, col] = df[col].str.strip()
if "Department" in df.columns:
    df.loc[:, "Department"] = df["Department"].replace({"Engineering": "Engineering", "ENGINEERING": "Engineering", "engineering": "Engineering"})
if "Gender" in df.columns:
    df.loc[:, "Gender"] = df["Gender"].replace({"Female": "Female", "female": "Female", "Male": "Male", "MALE": "Male", "Other": "Other"})
if "City" in df.columns:
    df.loc[:, "City"] = df["City"].replace({"delhi": "Delhi", "DELHI": "Delhi", "Delhi": "Delhi"})
if "Work_Mode" in df.columns:
    df.loc[:, "Work_Mode"] = df["Work_Mode"].replace({"REMOTE": "Remote", "remote": "Remote", "Remote": "Remote", "Office": "Office", "Hybrid": "Hybrid"})

# Final Check

In [32]:
df.info()
display(df.describe())
print(f"Shape: {df.shape}")
num_cols = ["Annual_Salary", "Age", "Experience_Years", "Performance_Score"]
for col in num_cols:
    if col in df.columns:
        print(f"Mean {col}: {df[col].mean()}")

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  3 non-null      int64
 1   Department   3 non-null      object
 2   Gender       3 non-null      object
 3   Age          3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 120.0+ bytes

       Employee_ID        Age
count          3.0   3.000000
mean         102.0  28.333333
std            1.0   2.886751
min          101.0  25.000000
25%          101.5  27.500000
50%          102.0  30.000000
75%          102.5  30.000000
max          103.0  30.000000

Shape: (3, 4)
Mean Age: 28.333333333333332

# Export CSV

In [33]:
df.to_csv("Day11_Cleaned_Company_Employee_Dataset.csv", index=False)
if os.path.exists("Day11_Cleaned_Company_Employee_Dataset.csv"):
    cleaned_df = pd.read_csv("Day11_Cleaned_Company_Employee_Dataset.csv")
    print(f"Cleaned Rows: {cleaned_df.shape[0]}")
    print(f"Total Missing: {cleaned_df.isnull().sum().sum()}")
    display(cleaned_df.head())

Cleaned Rows: 3
Total Missing: 0

   Employee_ID   Department  Gender   Age
0          101  Engineering    Male  30.0
1          102  Engineering    Male  30.0
2          103        Sales  Female  25.0